### ISSUE TITLE
Error 404 when downloading Kafka

### ISSUE THREAD

**Issue by cleankod** [eucuepo/vagrant-kafka#1]
The link `https://poole.im/files/kafka-0.8.0-9.x86_64.rpm` no longer works (that's right, https - since the http redirects here). Moreover, when it is https then it should have the `--no-check-certificate` parameter.

**Comment by justizin** [comment]
Looks like this is a continuance of the original work that led to that rpm:

  https://github.com/nielsbasjes/kafka-rpm

the jdk download failed for me as well, possibly because of the rpm subdir not existing, but we'll see.

I'll send a PR and ref this issue if I can make any improvement.  Ideally, automation like this wouldn't rely on someone's individual blog to host files.

**Comment by eucuepo** [comment]
Sorry, this was a PoC once and I'm don't maintain it, but I'll be happy to merge any fixes you submit

**Comment by justizin** [comment]
figured as much, happy to submit patches, surely I can get it working this week.

**Comment by justizin** [comment]
FYI, I have a (mostly) working 3-node vagrant env which uses community chef cookbooks to install java, zookeeper, and kafka at:

  https://github.com/bitmonk/bitmonk_kafka

each node in this setup has both zk and kafka running.

still have some interest in getting this one working, as when I finally deploy, I am likely to want rpms anyway.

**Comment by imarios** [comment]
I think this can be marked as closed as now the latest version works.

**Comment by eucuepo** [comment]
Fixed by @imarios PR https://github.com/eucuepo/vagrant-kafka/pull/3
